mongo_db:
  image: mongo:3.2.1

web:
  image: sasalatart/acm-kiosk
  command: npm start
  ports:
    - '80:8888'
  links:
    - mongo_db
  environment:
    - HOST
    - PORT
    - FB_CLIENT_ID
    - FB_CLIENT_SECRET
    - SECRET_TOKEN
